#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright (C) 2008 Wilson Pinto Júnior <wilsonpjunior@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import glob
import os
import gobject

if os.path.exists('data/ui'):
   os.remove('data/ui')

os.makedirs('data/ui')

glade_files = glob.glob('data/glade/*.glade')

for f in glade_files:
    ui_file = f.replace("glade", "ui")
    print "Converting: %s" % f
    cmd = "gtk-builder-convert %s %s" % (f, ui_file)
    ret = os.system(cmd)
    
    if ret != 0:
        print "Error:", cmd
        break
